# Generated by Django 5.2.3 on 2025-06-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hobbies',
            field=models.CharField(choices=[('Listening music', 'Listening music'), ('dancing', 'dancing'), ('story writing', 'story writing'), ('painting', 'painting'), ('others', 'others')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(choices=[('Tamil Nadu', 'Tamil Nadu'), ('Kerala', 'Kerala'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Telangana', 'Telangana'), ('Odisha', 'Odisha'), ('Karnataka', 'Karnataka'), ('Goa', 'Goa'), ('Haryana', 'Haryana'), ('Bihar', 'Bihar')], null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.CharField(choices=[('india', 'India')], null=True),
        ),
    ]
