# Generated by Django 5.2.3 on 2025-06-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0002_student_hobbies_student_state_alter_student_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='file',
            field=models.FileField(null=True, upload_to='mediafile'),
        ),
    ]
