# Generated by Django 5.2.3 on 2025-06-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0003_student_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(choices=[('Agasteeswaram', 'Agasteeswaram'), ('Anjugramam', 'Anjugramam'), ('Mylaudy', 'Mylaudy'), ('Aralvaimozhi', 'Aralvaimozhi'), ('Boothapandi', 'Boothapandi'), ('Azhagappapuram', 'Azhagappapuram'), ('Colachel', 'Colachel')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='district',
            field=models.CharField(choices=[('Kanniyakumari', 'Kanniyakumari'), ('Tirunelveli', 'Tirunelveli'), ('Thoothukudi', 'Thoothukudi'), ('Chennai', 'Chennai'), ('Coimbatore', 'Coimbatore'), ('Kanchipuram', 'Kanchipuram'), ('Vellore', 'Vellore')], null=True),
        ),
    ]
