# Generated by Django 5.2.3 on 2025-07-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0005_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employee',
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
