# Generated by Django 5.2.3 on 2025-07-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0007_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
