# Generated by Django 5.2.3 on 2025-07-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0011_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
