# Generated by Django 5.2.3 on 2025-07-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0012_alter_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('temp_password', models.CharField(max_length=100)),
                ('new_password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
